language: node_js
node_js:
  - "5.3"
compiler: clang-3.6
env:
  - CXX=clang-3.6
services:
  - mongodb
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8
before_script:
  # sometimes mongodb doesn't start in time so an artificial wait is added
  - sleep 15
script: "npm run-script test-travis"
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
after_success:
  - bash <(curl -s https://codecov.io/bash)